"""Portable core for the Yang Jian branching story generator."""

from .codec import (
    story_plan_from_dict,
    story_plan_from_json,
    story_plan_public_summary,
    story_plan_to_dict,
    story_plan_to_json,
)
from .generator import (
    AsyncStoryGenerator,
    GeneratedPlanInvalidError,
    StoryBrief,
    StoryGenerator,
)
from .models import (
    ArcKind,
    BranchTransition,
    CanonicalEvent,
    CharacterContext,
    Condition,
    ConditionOperator,
    Ending,
    MainArc,
    NarrativeFunction,
    NPCProfileSpec,
    NPCRequirement,
    PreferenceMeasure,
    PreferenceSnapshot,
    Secret,
    SideArc,
    StoryBeat,
    StoryPlan,
    StoryStandard,
)
from .validation import (
    Severity,
    StoryPlanValidator,
    ValidationIssue,
    ValidationReport,
)

__all__ = [
    "ArcKind",
    "AsyncStoryGenerator",
    "BranchTransition",
    "CanonicalEvent",
    "CharacterContext",
    "Condition",
    "ConditionOperator",
    "Ending",
    "GeneratedPlanInvalidError",
    "MainArc",
    "NarrativeFunction",
    "NPCProfileSpec",
    "NPCRequirement",
    "PreferenceMeasure",
    "PreferenceSnapshot",
    "Secret",
    "Severity",
    "SideArc",
    "StoryBeat",
    "StoryBrief",
    "StoryGenerator",
    "StoryPlan",
    "StoryPlanValidator",
    "StoryStandard",
    "ValidationIssue",
    "ValidationReport",
    "story_plan_from_dict",
    "story_plan_from_json",
    "story_plan_public_summary",
    "story_plan_to_dict",
    "story_plan_to_json",
]
